# Generated by Django 3.0.2 on 2021-02-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default='13-02-2021, 07:09:42'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(default='13-02-2021, 07:09:42'),
        ),
    ]
