# Generated by Django 3.0.2 on 2021-02-13 07:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210213_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 7, 19, 0, 169657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 7, 19, 0, 170363, tzinfo=utc)),
        ),
    ]
