# Generated by Django 3.0.2 on 2021-02-13 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210213_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 7, 25, 45, 941293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 13, 7, 25, 45, 941293, tzinfo=utc)),
        ),
    ]
