# Generated by Django 3.1.2 on 2021-02-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210213_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], max_length=1),
        ),
    ]
